config/routes.rb
Rails.application.routes.draw do

  root 'tasks#index'
  
  resources :tasks
end

app/models/task.rb
class Task < ActiveRecord::Base
	# validates :body, presence: true
	validates_presence_of :body
end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
	def index
		@tasks = Task.all
	end

	def show
		@task = Task.find(params[:id])
	end

	def new
		@task = Task.new
	end

	def edit
		@task = Task.find(params[:id])
	end

	def create
		@task = Task.new(task_params)
		if @task.save
			redirect_to '/'
		else
			render :new
		end
	end

	def update
		@task = Task.find(params[:id])
		if @task.update(task_params)
			redirect_to '/'
		else
			redirect_to edit_task_path(@task)
		end 
	end

	def destroy
		@task = Task.find(params[:id])
		if @task.destroy
			redirect_to '/'
		else
			redirect_to task_path(@task)
		end
	end

	private

	def task_params
		params.require(:task).permit(:body)
	end
end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todaylist</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= link_to 'Add new task', new_task_path %> 

<%= yield %>

</body>
</html>

app/views/tasks/edit.html.erb
<%= form_for @task do |f| %>
<%= f.text_field :body %>
<%= f.submit %> 
<% end %>  

app/views/tasks/index.html.erb
<ul>
<% @tasks.each do |task| %>
	<li><%= task.body %> <%= link_to 'delete', task_path(task), method: 'delete' %> <span> <%= link_to 'x', task_path(task), method: 'delete' %>  <%= link_to 'edit', edit_task_path(task) %>  </span> </li>
<% end %>
 </ul>

app/views/tasks/new.html.erb
<%= form_for @task do |f| %>
<%= f.text_field :body %>
<%= f.submit %> 
<% end %>

app/views/tasks/show.html.erb
<p><%= @task.body %> <span> <%= link_to 'x', task_path(@task), method: 'delete' %>  <%= link_to 'edit', edit_task_path(@task) %>  </span> </p>